### ISSUE TITLE
Finalize the navigation bar

### ISSUE THREAD

**Issue by andy6170** [battlefield-portal-community/portal-docs#14]
Currently there is no way to expand and hide sub categories and content
Ideally we need to make it easily configurable in the CSS
Categories should be coloured differently to sub categories and content to make it easier to read and distinguish.
Sub categories and content should be alphabetical
Agree on the layout

**Comment by The0zzy** [comment]
Current menu item should be aligned with portal style and get a light grey background with the turquoise text color.

![Screenshot 2023-10-14 113119](https://github.com/battlefield-portal-community/portal-docs/assets/105451431/1e6de11b-659f-4ad1-9adf-e4b1da4fb08b)

**Comment by The0zzy** [comment]
Sub categories should not be alphabetically but in a logical order. Additionally the Previous/Next buttons at the bottom of a page should be enabled. So that the documentation can be read like a book.
